name: Contented Strategy Blog
markdown: kramdown
paginate: 5
highlighter: 'rouge'
paginate_path: "blog/page:num"
description: Hannah Adcock Neil's blog on content strategy
url: https://contentedstrategy.com
exclude:
  - vendor
  - _vendor
  - .bundle
  - tmp
  - node_modules
kramdown:
  auto_ids: true
redcarpet:
  with_toc_data: true
sass:
  sass_dir: _vendor/foundation/scss/
plugins: [jekyll-paginate]