name: Contented Strategy Blog
markdown: redcarpet
paginate: 5
pygments: true
paginate_path: "blog/page:num"
description: Hannah Adcock Neil's blog on content strategy
url: http://contentedstrategy.com
exclude: ["vendor",".bundle"]
