name: Contented Strategy Blog
markdown: kramdown
paginate: 5
highlighter: true
paginate_path: "blog/page:num"
description: Hannah Adcock Neil's blog on content strategy
url: http://contentedstrategy.com
exclude: ["vendor",".bundle"]
kramdown:
  auto_ids: true
redcarpet:
  with_toc_data: true